package com.oldwei.isup.model;

import lombok.Data;
import java.io.Serial;
import java.io.Serializable;

@Data
public class GbDeviceChannel implements Serializable {
    @Serial
    private static final long serialVersionUID = 1L;

    private Integer id;
    private String deviceId;
    private String name;
    private String manufacturer;
    private String model;
    private String owner;
    private String civilCode;
    private String block;
    private String address;
    private Integer parental;
    private String parentId;
    private Integer safetyWay;
    private Integer registerWay;
    private String certNum;
    private Integer certifiable;
    private Integer errCode;
    private String endTime;
    private Integer secrecy;
    private String ipAddress;
    private Integer port;
    private String password;
    private String status;
    private Double longitude;
    private Double latitude;
    private Integer ptzType;
    private Integer positionType;
    private Integer roomType;
    private Integer useType;
    private Integer supplyLightType;
    private Integer directionType;
    private String resolution;
    private String businessGroupId;
    private String downloadSpeed;
    private Integer svcSpaceSupportMod;
    private Integer svcTimeSupportMode;
    private String createTime;
    private String updateTime;
    private Integer subCount;
    private String streamId;
    private Boolean hasAudio;
    private String gpsTime;
    private String streamIdentification;
    private Integer channelType;
    private String gbDeviceId;
    private String gbName;
    private String gbManufacturer;
    private String gbModel;
    private String gbOwner;
    private String gbCivilCode;
    private String gbBlock;
    private String gbAddress;
    private Integer gbParental;
    private String gbParentId;
    private Integer gbSafetyWay;
    private Integer gbRegisterWay;
    private String gbCertNum;
    private Integer gbCertifiable;
    private Integer gbErrCode;
    private String gbEndTime;
    private Integer gbSecrecy;
    private String gbIpAddress;
    private Integer gbPort;
    private String gbPassword;
    private String gbStatus;
    private Double gbLongitude;
    private Double gbLatitude;
    private String gbBusinessGroupId;
    private Integer gbPtzType;
    private Integer gbPositionType;
    private Integer gbRoomType;
    private Integer gbUseType;
    private Integer gbSupplyLightType;
    private Integer gbDirectionType;
    private String gbResolution;
    private String gbDownloadSpeed;
    private Integer gbSvcSpaceSupportMod;
    private Integer gbSvcTimeSupportMode;
    private Integer recordPlanId;
    private Integer dataType;
    private Integer dataDeviceId;
    private Double gpsSpeed;
    private Double gpsAltitude;
    private Double gpsDirection;
}
